"""Tests to verify that autogenerated example files match their source documentation."""

import subprocess
from pathlib import Path

import pytest


def test_doc_examples_are_up_to_date() -> None:
    """Ensure all autogenerated examples are up to date with their source docs.
    
    This test runs the extract_doc_examples.py script with the --check flag
    to validate that the autogenerated examples in examples/autogenerated/
    match the code blocks in their corresponding documentation files.
    
    If any files are out of sync, the script will exit with a non-zero code
    and the test will fail, providing information about which files need updating.
    """
    # Get the repo root
    repo_root = Path(__file__).parent.parent.parent
    
    # Path to the extract_doc_examples.py script
    script_path = "scripts/extract_doc_examples.py"
    
    # Run the script in check mode using uv
    result = subprocess.run(
        ["uv", "run", "python", script_path, "--check"],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
    )
    
    # If the script exits with a non-zero code, it means some files are out of sync
    if result.returncode != 0:
        # Print the output to provide context for the failure
        pytest.fail(
            f"Autogenerated examples are out of sync with their source docs!\n"
            f"STDOUT:\n{result.stdout}\n"
            f"STDERR:\n{result.stderr}\n"
            f"Run 'uv run python scripts/extract_doc_examples.py' to update them."
        )