#!/usr/bin/env python3
"""
Script to extract code examples from markdown documentation and save them
as Python files in examples/autogenerated.

Usage:
  extract_doc_examples.py                    # Update all examples
  extract_doc_examples.py --check            # Check all examples, exit 1 if any out of sync
  extract_doc_examples.py path/to/doc.md     # Update single example
  extract_doc_examples.py --check path/to/doc.md  # Check single example

This supports our type checking workflow by:
1. Extracting code blocks from markdown docs
2. Placing them in examples/autogenerated with proper structure
3. Maintaining a registry of which docs generate which examples
"""

import argparse
import difflib
import inspect
import os
import re
import sys
from pathlib import Path

# ruff: noqa: T201
# ^ Disables print warnings, which are intentional for this script

# Registry of markdown docs to autogenerated examples
# This maps documentation files to their corresponding autogenerated example files
DOC_TO_EXAMPLE_MAPPING: dict[str, str] = {
    "docs/learn/generations.md": "examples/autogenerated/generations.py",
    # Add more mappings as needed
}


def extract_python_code_blocks(md_file: str) -> list[str]:
    """Extract Python code blocks from a markdown file."""
    with open(md_file, encoding="utf-8") as f:
        content = f.read()

    # Find all Python code blocks
    code_blocks = re.findall(r'```python\n(.*?)```', content, re.DOTALL)
    return code_blocks


def generate_file_content(code_blocks: list[str], md_file: str) -> str:
    """Generate the content for the autogenerated file."""
    # Create the wrapper template
    wrapper_template = inspect.cleandoc(f"""
        # This file is automatically generated from documentation.
        # Do not edit directly. Changes will be overwritten.
        # Source: {os.path.basename(md_file)}
        
        from mirascope import llm
        from pydantic import BaseModel
        from typing import List, Dict, Any, Optional, Union, Awaitable, AsyncIterable
        import asyncio
        
        # Wrapper function to allow top-level awaits
        async def main_async():
    """)
    
    # Content pieces
    content_parts = [wrapper_template]
    
    # Add each code block properly indented
    for i, block in enumerate(code_blocks):
        # Clean the block of any common leading whitespace
        cleaned_block = inspect.cleandoc(block)
        
        # Add block header and indent all lines
        block_header = f"\n    # Code block {i+1}"
        indented_block = "\n".join(f"    {line}" for line in cleaned_block.split("\n"))
        
        content_parts.append(block_header)
        content_parts.append(indented_block)
        content_parts.append("\n")
    
    # Add execution code
    footer = inspect.cleandoc("""
        # For type checking only, won't be executed
        if __name__ == "__main__":
            asyncio.run(main_async())
    """)
    
    content_parts.append(footer)
    
    # Join all parts
    return "\n".join(content_parts)


def process_doc(
    md_path: str, py_path: str, check_mode: bool = False
) -> bool:
    """Process a single doc file, generating its example."""
    print(f"Processing {os.path.basename(md_path)}...")
    
    # Extract code blocks
    code_blocks = extract_python_code_blocks(md_path)
    if not code_blocks:
        print(f"Warning: No Python code blocks found in {md_path}")
        return False
    
    # Generate the new content
    new_content = generate_file_content(code_blocks, md_path)
    
    # Check if the file already exists
    file_exists = os.path.exists(py_path)
    
    if check_mode:
        if not file_exists:
            print(f"❌ Error: {py_path} does not exist!")
            return False
        
        # Read existing content
        with open(py_path, encoding="utf-8") as f:
            existing_content = f.read()
        
        # Compare contents
        if existing_content != new_content:
            print(f"❌ Error: {py_path} is out of sync with {md_path}")
            
            # Generate a unified diff for context
            diff = difflib.unified_diff(
                existing_content.splitlines(),
                new_content.splitlines(),
                fromfile=f"existing/{os.path.basename(py_path)}",
                tofile=f"generated/{os.path.basename(py_path)}",
                lineterm=''
            )
            for line in diff:
                print(line)
            
            return False
        else:
            print(f"✅ {py_path} is up to date")
            return True
    else:
        # Create parent directories if they don't exist
        os.makedirs(os.path.dirname(py_path), exist_ok=True)
        
        # Write the new content
        with open(py_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        
        print(f"{'Updated' if file_exists else 'Created'}: {py_path}")
        return True


def main() -> int:
    """Process all docs in the registry or a specific doc."""
    parser = argparse.ArgumentParser(
        description=inspect.cleandoc("""
            Extract code examples from markdown docs and generate Python files.
            
            If no doc path is provided, all docs in the registry will be processed.
            Use --check to verify files are up to date without modifying them.
        """)
    )
    parser.add_argument(
        "doc_path", 
        nargs="?", 
        help="Path to the markdown doc file (optional, if not provided all docs are processed)"
    )
    parser.add_argument(
        "-c", "--check", 
        action="store_true", 
        help="Check if autogenerated files are up to date without modifying them"
    )
    
    args = parser.parse_args()
    
    # Get the repo root
    repo_root = Path(__file__).parent.parent
    os.chdir(repo_root)
    
    # Determine which docs to process
    if args.doc_path:
        # Process a specific doc
        if args.doc_path not in DOC_TO_EXAMPLE_MAPPING:
            print(f"Error: {args.doc_path} not found in registry.")
            print("Known docs:")
            for doc in DOC_TO_EXAMPLE_MAPPING:
                print(f"  {doc}")
            return 1
        
        docs_to_process = {args.doc_path: DOC_TO_EXAMPLE_MAPPING[args.doc_path]}
    else:
        # Process all docs
        docs_to_process = DOC_TO_EXAMPLE_MAPPING
    
    # Process each doc
    success = True
    for md_path, py_path in docs_to_process.items():
        if not process_doc(md_path, py_path, args.check):
            success = False
    
    if args.check:
        if success:
            print("✅ All autogenerated files are up to date!")
        else:
            print("❌ Some autogenerated files are out of sync with their docs!")
    
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())